const {chromium}=require('playwright'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  assert.deepEqual(await page.locator('[data-tab]').allTextContents(),['Prioridades','Comparar municipios','Necesidad de recuperación temprana','Diagnóstico territorial','Fuentes y método']);
  assert.equal(await page.locator('.matrix-card').count(),3);
  const ids=await page.locator('[id]').evaluateAll(xs=>xs.map(x=>x.id));assert.equal(ids.length,new Set(ids).size);
  const abs=await page.locator('#matrix').innerText(),rel=await page.locator('#relative-matrix').innerText();
  const normal=await page.locator('#percapita-matrix tbody').innerText();
  const th=page.locator('#percapita-matrix [data-relative-sort="salud"]');
  await th.click();assert.equal(await th.locator('..').getAttribute('aria-sort'),'descending');
  await th.click();assert.equal(await th.locator('..').getAttribute('aria-sort'),'ascending');
  await th.click();assert.equal(await page.locator('#percapita-matrix tbody').innerText(),normal);
  await page.locator('#percapita-search').fill('pereira');
  assert.equal(await page.locator('#percapita-matrix tbody tr').count(),1);
  await page.locator('#percapita-matrix [data-relative-geo]').click();
  assert.match(await page.locator('#percapita-detail').innerText(),/cálculo per cápita/);
  assert.match(await page.locator('#percapita-detail').innerText(),/Habitantes/);
  await page.locator('#percapita-close').click();
  assert.equal(await page.locator('#matrix').innerText(),abs);assert.equal(await page.locator('#relative-matrix').innerText(),rel);
  await page.locator('#tab-radar').click();
  assert.equal(await page.locator('#radar .radar-layout').count(),3);
  const absLegend=await page.locator('#radar-legend').innerText(),relLegend=await page.locator('#radar-relative-legend').innerText();
  await page.locator('#radar-percapita-search-0').fill('pereira');
  assert.equal(await page.locator('#radar-percapita-results-0').getAttribute('class'),'radar-results');
  assert.equal(await page.locator('#radar-percapita-results-0 button').evaluate(el=>getComputedStyle(el).display),'block');
  await page.locator('#radar-percapita-search-0').press('ArrowDown');await page.keyboard.press('Enter');
  await page.locator('#radar-percapita-sectors [data-radar-m="0"][data-radar-axis="2"]').focus();
  assert.match(await page.locator('#radar-percapita-inspector').innerText(),/10.000 habitantes/);
  assert.match(await page.locator('#radar-percapita-inspector').innerText(),/Tasa =/);
  assert.equal(await page.locator('#radar-legend').innerText(),absLegend);
  assert.equal(await page.locator('#radar-relative-legend').innerText(),relLegend);
  await page.locator('#tab-rapida').click();
  assert.equal(await page.locator('#rapida #matrix, #priority-trend').count(),0);
  assert.ok(await page.locator('#scatter circle').count()>0);
  assert.equal(await page.locator('#comparison-axis, #comparison-panel, #comparison-warning').count(),0);
  assert.equal(await page.locator('#comparison-card .comparison-controls select, #comparison-card .comparison-controls input').count(),2);
  assert.deepEqual(await page.locator('#comparison-mode option').allTextContents(),['Absoluto','Per cápita','Relativo']);
  const checkPairs=async()=>{
    const expected=await page.evaluate(()=>Comparacion.compare(priorityModels,model,state,{mode:document.getElementById('comparison-mode').value,axis:'rank',panel:'available'}).pairs.map(r=>r.geo).sort());
    assert.deepEqual(await page.locator('[data-compare-geo]').evaluateAll(xs=>xs.map(x=>x.dataset.compareGeo).sort()),expected);
    assert.match(await page.locator('#comparison-chart').innerText(),/Puesto \(1 = mayor necesidad\)/);
  };
  await checkPairs();
  const decreePairs=await page.locator('[data-compare-geo]').count();
  const initial=await page.locator('#comparison-kpis').innerText();
  await page.locator('#comparison-mode').selectOption('percapita');
  assert.notEqual(await page.locator('#comparison-kpis').innerText(),initial);
  await checkPairs();
  await page.locator('#comparison-mode').selectOption('sectorial');
  await checkPairs();
  const stats=await page.locator('#comparison-kpis').innerText();
  await page.locator('#comparison-search').fill('pereira');
  assert.equal(await page.locator('.comparison-point.highlight').count(),1);
  assert.equal(await page.locator('#comparison-kpis').innerText(),stats);
  await page.locator('.comparison-point.highlight').focus();
  assert.match(await page.locator('#comparison-detail').innerText(),/Pereira/);
  assert.match(await page.locator('#comparison-detail').innerText(),/Cobertura:/);

  await page.locator('#comparison-mode').selectOption('absolute');
  await checkPairs();
  await page.locator('#scope').selectOption('all');
  await checkPairs();
  assert.ok(await page.locator('[data-compare-geo]').count()>=decreePairs);
  assert.equal(await page.locator('#comparison-mode').inputValue(),'absolute');
  await page.locator('#dept').selectOption('Risaralda');
  await checkPairs();
  assert.ok(await page.locator('[data-compare-geo]').count()<decreePairs);
  assert.match(await page.locator('#comparison-note').innerText(),/Risaralda/);
  await page.locator('#dept').selectOption('');
  await checkPairs();
  assert.doesNotMatch(await page.locator('body').innerText(),/recuperación RAPIDA/i);
  await page.locator('#rapida-search').fill('pereira');
  assert.equal(await page.locator('#rapida-table tbody tr').count(),1);
  if(process.env.UNIFIED_SCREENSHOT)await page.locator('#comparison-card').screenshot({path:process.env.UNIFIED_SCREENSHOT});
  await page.setViewportSize({width:390,height:844});
  for(const tab of ['rapida','radar','prioridades','diagnostico','metodo']){
    await page.locator('#tab-'+tab).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+tab);
  }
  await page.locator('#tab-rapida').click();
  await page.locator('#comparison-detail [data-geo]').click();
  assert.equal(await page.locator('#diagnostico').isVisible(),true);
  assert.match(await page.locator('#profile-note').innerText(),/Pereira/);
  assert.deepEqual(errors,[]);
  console.log('Unified UI OK: 3 matrices, 3 independent radars, RAPIDA, paired comparison, statistics, search, keyboard, mobile, diagnostic.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
